apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: context-alarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        reloader.stakater.com/auto: "true"
        secret.reloader.stakater.com/reload: "api-secret"
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: api
          image: ghcr.io/context-alarm/context-alarm-backend:65f2c614bf3c569ac1c4193164398ee68813e4f9
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: api-secret
          ports:
            - containerPort: 9090
