apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: context-alarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        context-alarm.dev/dummy-rollout: "2026-03-18T00:00:00Z"
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: api
          image: ghcr.io/context-alarm/context-alarm-backend:4a2e3bd2d9522dc5dc977a32c0fef7557943485e
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: api-secret
          ports:
            - containerPort: 9090
