apiVersion: apps/v1
kind: Deployment
metadata:
  name: checker-api
  namespace: context-alarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checker-api
  template:
    metadata:
      labels:
        app: checker-api
      annotations:
        reloader.stakater.com/auto: "true"
        secret.reloader.stakater.com/reload: "api-secret"
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: checker-api
          image: ghcr.io/context-alarm/context-alarm-trigger:c4d7aaf45fc808ff99365a4e5bbad399a1f4fcb5
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: api-secret
